"""Tests for the Console Pydantic models generated by ``doit console_models``.

The generated tree under ``src/pynetappfoundry/models/console/`` is committed
in-tree (per ADR-0008's Console amendment) and produced by
``datamodel-code-generator`` from the OpenAPI 3.0.3 spec at
``tools/console_openapi/generated/console_openapi.yaml``. These tests guard
three properties:

* the package imports cleanly (catches packaging / ``__init__.py`` regressions);
* representative payloads validate and round-trip through ``model_dump`` with
  kebab-case aliases preserved (catches generator-flag drift, e.g. losing
  ``populate_by_name`` or ``alias`` annotations);
* the determinism check (``doit console_models_check``) is intentionally
  excluded here because it shells out to the generator and ``git`` and is
  not appropriate for a fast unit-test run; it lives in CI as a separate
  doit task. See the module docstring of
  ``tools/doit/console_openapi_tasks.py`` for the rationale.
"""

from __future__ import annotations

import importlib
import json
from pathlib import Path

import pytest

FIXTURES = Path(__file__).resolve().parents[3] / "fixtures" / "console_models"


# --- Smoke import test -------------------------------------------------------


@pytest.mark.parametrize(
    "module_path",
    [
        "pynetappfoundry.models.console",
        "pynetappfoundry.models.console.tenancy",
        "pynetappfoundry.models.console.tenancyv4",
        "pynetappfoundry.models.console.tenancy.post_tenancy_account_service_account",
        "pynetappfoundry.models.console.tenancyv4.get_organizations",
        "pynetappfoundry.models.console.tenancyv4.get_folders",
    ],
)
def test_generated_module_imports(module_path: str) -> None:
    """Importing representative generated modules must not raise.

    Catches packaging regressions (missing ``__init__.py``, broken relative
    imports inside generated files, and missing Pydantic dependencies).
    """
    module = importlib.import_module(module_path)
    assert module.__file__ is not None
    assert module.__file__.endswith(".py")


# --- Representative payload validation roundtrip -----------------------------


def test_service_account_body_validates() -> None:
    """A POST /tenancy/account/service-account body parses cleanly.

    Exercises the simplest shape (flat ``BaseModel`` with required +
    optional fields, no aliases). A failure here indicates the generator
    dropped a field or changed required-ness.
    """
    from pynetappfoundry.models.console.tenancy.post_tenancy_account_service_account import (
        Body,
    )

    payload = json.loads((FIXTURES / "service_account_body.json").read_text())
    model = Body.model_validate(payload)

    assert model.serviceAccountName == "ci-bot"
    assert model.rolePublicId == "role-AAAAAAAAAAA"
    assert model.workspacePublicIds == ["ws-BBBBBBBBBBB", "ws-CCCCCCCCCCC"]


def test_organization_response_validates_and_roundtrips_with_aliases() -> None:
    """A GET /v1/management/organizations/{id} response roundtrips losslessly.

    This is the load-bearing roundtrip test: the payload contains
    ``links[].hints.accept-post`` and ``accept-put``, which use kebab-case
    keys in the JSON. The generated ``Hints`` model exposes those as
    Python attributes ``accept_post`` / ``accept_put`` with
    ``alias="accept-post"`` / ``alias="accept-put"``. ``model_dump(by_alias=True)``
    must restore the kebab-case keys; if the generator stops emitting
    aliases, the dumped output will use snake_case and this assertion
    will catch it.
    """
    from pynetappfoundry.models.console.tenancyv4.get_organizations import (
        Resource10GetResponseBody,
    )

    payload = json.loads((FIXTURES / "organization_response.json").read_text())
    model = Resource10GetResponseBody.model_validate(payload)

    # Required fields must round-trip.
    assert model.id == "org-DDDDDDDDDDD"
    assert model.name == "Acme"
    assert model.resourceClass == "ORG"

    # Nested ``Hints`` must use snake_case attribute access for kebab keys.
    assert model.links is not None
    hint = model.links[0].hints
    assert hint is not None
    assert hint.accept_post is not None  # alias="accept-post"
    assert hint.accept_put is not None  # alias="accept-put"

    # Roundtrip with by_alias=True must restore the kebab-case shape.
    dumped = model.model_dump(by_alias=True, exclude_none=True)
    assert dumped["links"][0]["hints"]["accept-post"] == {}
    assert dumped["links"][0]["hints"]["accept-put"] == {}
    assert dumped["links"][0]["hints"]["allow"] == ["GET", "PUT", "DELETE"]


def test_organization_response_rejects_missing_required_field() -> None:
    """The generator must keep ``required`` fields required.

    If a downstream generator change loses the OpenAPI ``required: [...]``
    list, every field becomes optional and validation silently passes for
    any payload. This test hard-codes the expectation that ``id`` is
    required on ``Resource10GetResponseBody``.
    """
    from pydantic import ValidationError

    from pynetappfoundry.models.console.tenancyv4.get_organizations import (
        Resource10GetResponseBody,
    )

    payload = json.loads((FIXTURES / "organization_response.json").read_text())
    payload.pop("id")
    with pytest.raises(ValidationError):
        Resource10GetResponseBody.model_validate(payload)


# --- Hash map (RootModel) shape ---------------------------------------------


def test_tags_root_model_accepts_string_string_dict() -> None:
    """Hash-mapping definitions render as ``RootModel[dict[str, str]]``.

    The OpenAPI spec's ``additionalProperties: {type: string}`` must compile
    to ``RootModel`` rather than a placeholder ``BaseModel``. A failure
    here usually means the spec lost ``additionalProperties`` or the
    generator changed how it represents free-form maps.
    """
    from pynetappfoundry.models.console.tenancyv4.get_organizations import Tags

    tags = Tags.model_validate({"env": "prod", "owner": "platform"})
    assert tags.root == {"env": "prod", "owner": "platform"}
    assert tags.model_dump() == {"env": "prod", "owner": "platform"}
