# generated by datamodel-codegen:
#   filename:  console_openapi.yaml

from __future__ import annotations

from pydantic import BaseModel, Field


class Body(BaseModel):
    serviceAccountName: str | None = Field(None, description="Service account name")
    rolePublicId: str | None = Field(None, description="Service account role")
    workspacePublicIds: list[str] | None = Field(None, description="Service account workspaces")
