# generated by datamodel-codegen:
#   filename:  console_openapi.yaml

from __future__ import annotations

from pydantic import BaseModel


class Body(BaseModel):
    accountId: str
    userId: str | None = None
    resourceIdentifier: str | None = None
    agentId: str | None = None
