# generated by datamodel-codegen:
#   filename:  console_openapi.yaml

from __future__ import annotations

from pydantic import BaseModel


class Metadata(BaseModel):
    propertyName: str
    propertyValue: str


class Body(BaseModel):
    workspacePublicId: str
    agentId: str
    resourceIdentifier: str
    name: str | None = None
    resourceType: str | None = None
    resourceClass: str | None = None
    cloudId: str | None = None
    metadata: Metadata | None = None
