# generated by datamodel-codegen:
#   filename:  console_openapi.yaml

from __future__ import annotations

from pydantic import BaseModel


class Metadata(BaseModel):
    propertyName: str
    propertyValue: str


class Body(BaseModel):
    cloudId: str | None = None
    metadata: Metadata | None = None
