# generated by datamodel-codegen:
#   filename:  console_openapi.yaml

from __future__ import annotations

from pydantic import BaseModel


class Body(BaseModel):
    resourceIdentifier: str
    action: str
    accountId: str | None = None
