# generated by datamodel-codegen:
#   filename:  console_openapi.yaml

from __future__ import annotations

from pydantic import BaseModel, Field


class Body(BaseModel):
    associatedEmail: str | None = Field(
        None, description="User email to be associated with the account"
    )
    rolePublicId: str | None = Field(
        None,
        description="User role name. For example, use Role-1 for account admin or Role-2 for workspace admin.",
    )
