# generated by datamodel-codegen:
#   filename:  console_openapi.yaml

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class AcceptPost(BaseModel):
    """
    accept-post

    Provides details about which media types are accepted when creating a resource.
    """


class AcceptPut(BaseModel):
    """
    accept-put

    Indicates details about what media types are accepted when updating a resource.
    """


class Hints(BaseModel):
    accept_post: AcceptPost | None = Field(
        None,
        alias="accept-post",
        description="Provides details about which media types are accepted when creating a resource.",
    )
    accept_put: AcceptPut | None = Field(
        None,
        alias="accept-put",
        description="Indicates details about what media types are accepted when updating a resource.",
    )
    allow: list[str] | None = Field(
        None,
        description='An array of methods that can be used to interact with the link target. Defined values for collections: "POST" - Indicates if new resources can be created in the collection. Defined values for resources: "PUT" - Indicates if the resource can be modified "DELETE" - Indicates if the resource can be deleted',
    )
    permissions: list[str] | None = Field(
        None, description="List of the permissions required to use the link."
    )
    status: str | None = Field(
        None,
        description='Indicates if the target of the link is deprecated. Defined values are: "deprecated"',
    )


class TargetSchema(BaseModel):
    """
    targetSchema

    Link to a JSON schema that can be used to validate the target of the link (response body).

    The preferred format is a $ref link to an external schema.

    This field is optional and should only be included when there is a known schema for the target of the href.

    See https://json-schema.org/draft/2019-09/json-schema-hypermedia.html#rfc.section.9.2 for more details.
    """


class TypeBxpLink(BaseModel):
    hints: Hints | None = None
    href: str = Field(..., description="String describing a relative URI.")
    rel: str = Field(
        ...,
        description="The type of relationship for the link. Values are defined in the IANA Link Relationships registry, or an extension relationship type as specified in section 2.1.2 of RFC 8288.",
    )
    targetSchema: TargetSchema | None = Field(
        None,
        description="Link to a JSON schema that can be used to validate the target of the link (response body). The preferred format is a $ref link to an external schema. This field is optional and should only be included when there is a known schema for the target of the href. See https://json-schema.org/draft/2019-09/json-schema-hypermedia.html#rfc.section.9.2 for more details.",
    )
    title: str | None = Field(
        None,
        description="Label of a link such that it can be used as a human-readable identifier (e.g., a menu entry). Minimum length: 0 Maximum length: 1023",
    )
    type: str | None = Field(
        None,
        description="The media type of the target of the href. This field is optional and should be included when there is a known media type for the target of the href. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link for more details.",
    )


class TypeBxpLabel(BaseModel):
    name: str = Field(..., description="Name of the label.")
    value: str = Field(..., description="Value of the label.")


class TypeBxpMetadata(BaseModel):
    createdBy: str | None = Field(None, description="UUID of the user who created the resource.")
    creationTimestamp: str | None = Field(None, description="Resource creation date.")
    labels: list[TypeBxpLabel] | None = Field(
        None,
        description="Array of name/value pairs representing additional information for the resource.",
    )
    modificationTimestamp: str | None = Field(None, description="Resource modification date.")
    modifiedBy: str | None = Field(None, description="UUID of the user who modified the resource.")


class User10PublicKeyGetResponseBody(BaseModel):
    audience: str | None = Field(
        None,
        description="The value that must be included in the 'audience' claim of the private key JWT token.",
    )
    credentialId: str | None = Field(
        None, description="The Auth0 credential ID associated with the public key."
    )
    expirationTimestamp: str | None = Field(
        None, description="The date and time when the public key expires."
    )
    fingerprint: str | None = Field(
        None,
        description="The SHA-1 fingerprint of the public X.509 certificate or RSA key that was provided for the public key.",
    )
    id: str = Field(
        ...,
        description="Globally unique identifier of the resource conforming to the UUIDv4 schema.",
    )
    keyType: str | None = Field(None, description="Type of the public key. Defined values are:")
    metadata: TypeBxpMetadata | None = Field(
        None, description="Metadata associated with the resource."
    )
    state: str | None = Field(None, description="The state of the public key. Defined values are:")
    type: str = Field(..., description="Media type of the resource. Defined values are:")
    version: str = Field(..., description="Version of the resource. Defined values are:")


class ServiceAccount(BaseModel):
    audience: str | None = Field(
        None,
        description="The value that must be included in the 'audience' claim of the private key JWT token.",
    )
    authenticationMethod: str | None = Field(
        None,
        description="Authentication method used by the service account. Defined values are:",
    )
    expirationNotificationPeriod: str | None = Field(
        None,
        description="The time period when expiration notifications are generated. Defined values are:",
    )
    publicKeys: list[User10PublicKeyGetResponseBody] | None = Field(
        None, description="List of public keys associated with the service account."
    )


class Tags(RootModel[dict[str, str]]):
    """
    tags
    Hash mapping strings to string
    """

    root: dict[str, str]


class InvalidParams(BaseModel):
    name: str = Field(..., description="Name of the invalid parameter.")
    reason: str = Field(..., description="Reason why the parameter is invalid.")
