# generated by datamodel-codegen:
#   filename:  console_openapi.yaml

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class AcceptPost(BaseModel):
    """
    accept-post

    Provides details about which media types are accepted when creating a resource.
    """


class AcceptPut(BaseModel):
    """
    accept-put

    Indicates details about what media types are accepted when updating a resource.
    """


class Hints(BaseModel):
    accept_post: AcceptPost | None = Field(
        None,
        alias="accept-post",
        description="Provides details about which media types are accepted when creating a resource.",
    )
    accept_put: AcceptPut | None = Field(
        None,
        alias="accept-put",
        description="Indicates details about what media types are accepted when updating a resource.",
    )
    allow: list[str] | None = Field(
        None,
        description='An array of methods that can be used to interact with the link target. Defined values for collections: "POST" - Indicates if new resources can be created in the collection. Defined values for resources: "PUT" - Indicates if the resource can be modified "DELETE" - Indicates if the resource can be deleted',
    )
    permissions: list[str] | None = Field(
        None, description="List of the permissions required to use the link."
    )
    status: str | None = Field(
        None,
        description='Indicates if the target of the link is deprecated. Defined values are: "deprecated"',
    )


class TargetSchema(BaseModel):
    """
    targetSchema

    Link to a JSON schema that can be used to validate the target of the link (response body).

    The preferred format is a $ref link to an external schema.

    This field is optional and should only be included when there is a known schema for the target of the href.

    See https://json-schema.org/draft/2019-09/json-schema-hypermedia.html#rfc.section.9.2 for more details.
    """


class TypeBxpLink(BaseModel):
    hints: Hints | None = None
    href: str = Field(..., description="String describing a relative URI.")
    rel: str = Field(
        ...,
        description="The type of relationship for the link. Values are defined in the IANA Link Relationships registry, or an extension relationship type as specified in section 2.1.2 of RFC 8288.",
    )
    targetSchema: TargetSchema | None = Field(
        None,
        description="Link to a JSON schema that can be used to validate the target of the link (response body). The preferred format is a $ref link to an external schema. This field is optional and should only be included when there is a known schema for the target of the href. See https://json-schema.org/draft/2019-09/json-schema-hypermedia.html#rfc.section.9.2 for more details.",
    )
    title: str | None = Field(
        None,
        description="Label of a link such that it can be used as a human-readable identifier (e.g., a menu entry). Minimum length: 0 Maximum length: 1023",
    )
    type: str | None = Field(
        None,
        description="The media type of the target of the href. This field is optional and should be included when there is a known media type for the target of the href. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link for more details.",
    )


class TypeBxpLabel(BaseModel):
    name: str = Field(..., description="Name of the label.")
    value: str = Field(..., description="Value of the label.")


class TypeBxpMetadata(BaseModel):
    createdBy: str | None = Field(None, description="UUID of the user who created the resource.")
    creationTimestamp: str | None = Field(None, description="Resource creation date.")
    labels: list[TypeBxpLabel] | None = Field(
        None,
        description="Array of name/value pairs representing additional information for the resource.",
    )
    modificationTimestamp: str | None = Field(None, description="Resource modification date.")
    modifiedBy: str | None = Field(None, description="UUID of the user who modified the resource.")


class Grant10GetExtendedResourceResponseBody(BaseModel):
    resourceClass: str | None = Field(
        None, description="JSON string containing the resource class."
    )
    resourceId: str | None = Field(
        None,
        description="Globally unique identifier of the resource. Defined values are:",
    )
    resourceName: str | None = Field(None, description="JSON string containing the resource name.")
    resourceType: str | None = Field(None, description="JSON string containing the resource type.")


class Tags(RootModel[dict[str, str]]):
    """
    tags
    Hash mapping strings to string
    """

    root: dict[str, str]


class Grant10GetExtendedUserResponseBody(BaseModel):
    lastLoginDate: str | None = Field(
        None, description="The date and time when the user last logged in."
    )
    userEmail: str | None = Field(None, description="User email address.")
    userId: str | None = Field(
        None, description="Globally unique identifier of the user. Defined values are:"
    )
    userName: str | None = Field(None, description="JSON string containing the user name.")


class InvalidParams(BaseModel):
    name: str = Field(..., description="Name of the invalid parameter.")
    reason: str = Field(..., description="Reason why the parameter is invalid.")
