# generated by datamodel-codegen:
#   filename:  console_openapi.yaml

from __future__ import annotations

from pydantic import BaseModel, Field


class TypeBxpLabel(BaseModel):
    name: str = Field(..., description="Name of the label.")
    value: str = Field(..., description="Value of the label.")


class TypeBxpMetadata(BaseModel):
    createdBy: str | None = Field(None, description="UUID of the user who created the resource.")
    creationTimestamp: str | None = Field(None, description="Resource creation date.")
    labels: list[TypeBxpLabel] | None = Field(
        None,
        description="Array of name/value pairs representing additional information for the resource.",
    )
    modificationTimestamp: str | None = Field(None, description="Resource modification date.")
    modifiedBy: str | None = Field(None, description="UUID of the user who modified the resource.")


class User10PublicKeyGetResponseBody(BaseModel):
    audience: str | None = Field(
        None,
        description="The value that must be included in the 'audience' claim of the private key JWT token.",
    )
    credentialId: str | None = Field(
        None, description="The Auth0 credential ID associated with the public key."
    )
    expirationTimestamp: str | None = Field(
        None, description="The date and time when the public key expires."
    )
    fingerprint: str | None = Field(
        None,
        description="The SHA-1 fingerprint of the public X.509 certificate or RSA key that was provided for the public key.",
    )
    id: str = Field(
        ...,
        description="Globally unique identifier of the resource conforming to the UUIDv4 schema.",
    )
    keyType: str | None = Field(None, description="Type of the public key. Defined values are:")
    metadata: TypeBxpMetadata | None = Field(
        None, description="Metadata associated with the resource."
    )
    state: str | None = Field(None, description="The state of the public key. Defined values are:")
    type: str = Field(..., description="Media type of the resource. Defined values are:")
    version: str = Field(..., description="Version of the resource. Defined values are:")
