# generated by datamodel-codegen:
#   filename:  console_openapi.yaml

from __future__ import annotations

from pydantic import BaseModel, Field


class Users(BaseModel):
    aadId: str | None = None
    auth0Id: str | None = None
    emailId: str | None = None
    userId: str | None = None


class InvalidParams(BaseModel):
    name: str = Field(..., description="Name of the invalid parameter.")
    reason: str = Field(..., description="Reason why the parameter is invalid.")
