# generated by datamodel-codegen:
#   filename:  console_openapi.yaml

from __future__ import annotations

from pydantic import BaseModel, Field


class Usergroups(BaseModel):
    id: str | None = Field(
        None,
        description="Globally unique identifier of the resource. Defined values are:",
    )
    name: str | None = Field(
        None,
        description="JSON string containing a name for the user group. Defined values are:",
    )


class InvalidParams(BaseModel):
    name: str = Field(..., description="Name of the invalid parameter.")
    reason: str = Field(..., description="Reason why the parameter is invalid.")
