# generated by datamodel-codegen:
#   filename:  console_openapi.yaml

from __future__ import annotations

from pydantic import BaseModel, Field


class InvalidParams(BaseModel):
    name: str = Field(..., description="Name of the invalid parameter.")
    reason: str = Field(..., description="Reason why the parameter is invalid.")
