# generated by datamodel-codegen:
#   filename:  console_openapi.yaml

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel


class TypeBxpLabel(BaseModel):
    name: str = Field(..., description="Name of the label.")
    value: str = Field(..., description="Value of the label.")


class TypeBxpMetadata(BaseModel):
    createdBy: str | None = Field(None, description="UUID of the user who created the resource.")
    creationTimestamp: str | None = Field(None, description="Resource creation date.")
    labels: list[TypeBxpLabel] | None = Field(
        None,
        description="Array of name/value pairs representing additional information for the resource.",
    )
    modificationTimestamp: str | None = Field(None, description="Resource modification date.")
    modifiedBy: str | None = Field(None, description="UUID of the user who modified the resource.")


class Tags(RootModel[dict[str, str]]):
    """
    tags
    Hash mapping strings to string
    """

    root: dict[str, str]


class InvalidParams(BaseModel):
    name: str = Field(..., description="Name of the invalid parameter.")
    reason: str = Field(..., description="Reason why the parameter is invalid.")
