[settings]
type='data'

[aiqums.AIQUM-Prod]
ip='192.168.1.150'
div='ITS'
bu='LAR'
env='Prod'

[connectors.CONNECTOR-PROD-01]
ip='192.168.1.132'
div='ITS'
bu='LAR'
env='Prod'

[clusters.CLUSTER-PROD-01]
ip='192.168.1.173'
div='ITS'
bu='LAR'
app='Storage'
env='PD'
subapp='PD1'
tags=['active', 'nfs']
region='USCU'

[aiqums.AIQUM-LT]
ip='192.168.2.150'
div='ITS'
bu='LAR'
env='LT'

[connectors.CONNECTOR-LT-01]
ip='192.168.2.132'
div='ITS'
bu='LAR'
env='LT'

[clusters.CLUSTER-LT-01]
ip='192.168.2.173'
div='ITS'
bu='LAR'
app='Storage'
env='LT'
subapp='LT1'
tags=['active', 'nfs']
region='USCU'

[aiqums.AIQUM-DEV]
ip='192.168.3.150'
div='ITS'
bu='LAR'
env='Dev'

[connectors.CONNECTOR-DEV-01]
ip='192.168.3.132'
div='ITS'
bu='LAR'
env='Dev'

[clusters.CLUSTER-DEV-01]
ip='192.168.3.173'
div='ITS'
bu='LAR'
app='Storage'
env='Dev'
subapp='Dev1'
tags=['active', 'nfs']
region='USCU'
